config/routes.rb
Rails.application.routes.draw do
  resources :events, only: [:show,:index,:create] do 
    resources :items, only: [:create]
  	resources :assignments, only:[:create]
  end

  root 'incio#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
# == Schema Information
#
# Table name: assignments
#
#  id         :integer          not null, primary key
#  usuario    :string
#  cantidad   :integer
#  event_id   :integer
#  item_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Assignment < ApplicationRecord
	validates :usuario, presence: {message: "Campo obligatorio"}
	validates :cantidad, presence: {message: "Campo obligatorio"}, numericality: {only_integer: true}
	#relaciones
	#has_many :usuario_items, dependent: :destroy
	#has_many :items, :through => :usuario_items
	belongs_to :event
	belongs_to :item
	
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  nombre      :string
#  descripcion :text
#  item_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Event < ApplicationRecord
	validates :nombre, presence: {message: "Campo obligatorio."}
	has_many :items
	has_many :assignments
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id              :integer          not null, primary key
#  numero          :integer
#  numero_original :integer
#  descripcion     :string
#  completado      :boolean          default(FALSE)
#  event_id        :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Item < ApplicationRecord
	#validaciones
	validates :numero, presence: {message: "Campo obligatorio"}, numericality: {only_integer: true}
	validates :descripcion, presence: {message: "Campo obligatorio"}
	#relaciones
	belongs_to :event
	has_many :assignments, dependent: :destroy
	#has_many :usuario_items, dependent: :destroy
	#has_many :assignments, :through => :usuario_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  def create
    #raise @assignment
    @event = Event.find(params[:event_id])
    @assignment = @event.assignments.new(assignment_params)
    @assignment.event = @event

    if params[:itemusuario] != nil # si no selecciono nada
      @item =Item.find(params[:itemusuario])
      @assignment.item_id = params[:itemusuario]
      if @assignment.cantidad <= @item.numero #si trae mas de lo que se pide
          respond_to do |format|
            if @assignment.save
              if (@item.numero-@assignment.cantidad) == 0
                @item.update(completado: true)
                flash[:error] = "#{@item.descripcion} se completo"
              end
              @item.update(numero:(@item.numero-@assignment.cantidad))
              format.html { redirect_to @assignment.event, notice: 'asignacion creada'}
            else
              flash[:error] = 'No se pudo agregar, revise los datos'
              format.html { redirect_to @event}
            end
          end
      else
        flash[:error] = 'Gracias por la solidaridad, pero no nececitamos tanto'
        return redirect_to @event
      end
    else
      flash[:error] = 'Seleccione algo para traer!'
      return redirect_to @event
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:usuario,:cantidad,:itemusuario)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]

  def index
    redirect_to root_path
  end

  def show
    @item = Item.new
    @assignment = Assignment.new
  end


  # POST /events
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Evento creado satisfactoriamente' }
      else
        flash[:error] = 'Debe llenar todos los campos del evento'
        format.html {redirect_to root_path}
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:nombre, :descripcion)
    end
end

app/controllers/incio_controller.rb
class IncioController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # POST /items
  def create
    @event = Event.find(params[:event_id])
    @item = @event.items.new(item_params)
    @item.event = @event
    @item.numero_original = @item.numero
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item.event, notice: 'Item agregado correctamente' }
      else
        flash[:error] = 'No se pudo agregar, revise los datos'
        format.html { redirect_to @event}
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:numero, :descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/incio_helper.rb
module IncioHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/usuario_items_helper.rb
module UsuarioItemsHelper
end

app/views/assignments/_form.html.haml
= form_for ([@event,@assignment]) do |f|
	.col.s12
		- if @assignment.errors.any?
			.red.lighten-2{style:"padding:10px"}
				%i.material-icons.left warning
				%h6= "#{pluralize(@assignment.errors.count, "problema(s)")} ocurrió al guardar el evento"
			-@assignment.errors.full_messages.each do |message|
				%script Materialize.toast("#{message}", 5000);
		.row
			.input-field.col.s12.l4
				%i.material-icons.prefix filter_9_plus
				= f.text_field :cantidad
				= f.label :cantidad
			.input-field.col.s12.l8
				%i.material-icons.prefix account_circle
				= f.text_field :usuario
				= f.label :usuario, "Nombre de quien trae"
			%h5 Disponibles: 
			-@event.items.reverse.each do |it|
				-if it.numero != 0
					= radio_button_tag :itemusuario,it.id
					= label_tag "itemusuario_#{it.id}", it.descripcion
					&nbsp;&nbsp;&nbsp;&nbsp;
			.input-field.col.s12
				%br
				%a.btn.waves-effect.waves-light.modal-trigger.green{:href => "#modal4"} Traer item
				#modal4.modal
					.modal-content
						%h4.truncate ¿Esta seguro que desea traer este item?
						%ul
							%li *No va a poder editar esta selcción posteriormente
							%li *No va a poder eliminar esta decisión
					.modal-footer
						= f.submit 'Traer', :class=>"btn"
						%a.modal-action.modal-close.waves-effect.waves-green.btn-flat REGRESAR

app/views/events/_form.html.haml
= form_for @event,:html=>{:class=>"row"}  do |f|
	.col.s12
		- if @event.errors.any?
			.red.lighten-2{style:"padding:10px"}
				%i.material-icons.left warning
				%h6= "#{pluralize(@event.errors.count, "problema(s)")} ocurrió al guardar el evento"
			-@event.errors.full_messages.each do |message|
				%script Materialize.toast("#{message}", 5000);

		.row
			.input-field.col.s12
				%i.material-icons.prefix event
				= f.text_field :nombre
				= f.label :nombre
			.input-field.col.s12
				%i.material-icons.prefix reorder
				= f.text_area :descripcion, :class => "materialize-textarea",:data=>{:length=>"400"}
				= f.label :descripcion
			.input-field.btn.waves-effect.waves-light
				= f.submit "Crear"

app/views/events/show.html.haml
-u=0
-@event.items.reverse.each do |i| 
	-u+=i.numero_original.to_i
-traen=0
-@event.assignments.each do |i| 
	-traen+=i.cantidad.to_i
-if u != 0
	-porcentaje = (traen*100)/u
-else
	-porcentaje=0

.fixed-action-btn
	%a.btn-floating.btn-large.red.modal-trigger.tooltipped{:href => "#modal1", :data=>{:position=>"top", :delay=>"50", :tooltip=>"Crear nuevo evento"}}
		%i.large.material-icons add
#modal3.modal.bottom-sheet
	.modal-content
		%h4.truncate Historial
		%ul.collection
			-@event.assignments.reverse.each do |e| 
				%li.collection-item.avatar
					%i.material-icons.circle.green account_box
					%span.title #{e.usuario.capitalize}
					%p va a traer #{e.cantidad} #{e.item.descripcion} <br/> #{time_ago_in_words(e.created_at)} ago
					%p.secondary-content
						%i.material-icons done
%br/
%br/
%br/
.container
	.row
		.col.s12.m6.light-green.lighten-5.card-panel
			.col.s12
				%h4.truncate
					= @event.nombre.upcase
			.col.s12
				%h6
					= @event.descripcion
			.col.s12
				%br/
				%br/
				%br/
				%strong Progreso #{porcentaje}%:
				%br
				%a.modal-trigger{:href => "#modal3"}  Ver historial
				.progress
					-if porcentaje == 0
						"<div class="indeterminate"></div>"
					-else
						"<div class="determinate" style="width: #{porcentaje}%"></div>".html_safe
		-#.col.l1
		.col.s12.m6.card-panel.hoverable
			%h5.truncate Agregar item:
			%blockquote *Llene ambos campos
			=render "items/form"
			%br/
			%br/
		.col.s12.m6.card-panel.hoverable
			%h5.truncate Traer Item
			%blockquote *Seleccione algun item y llene los campos
			=render "assignments/form"
		.col.s12.m6
			%h5.truncate Items y asignaciones:
			%ul.collapsible{data:{collapsible:"accordion"}}
				-@event.items.reverse.each do |i| 
					%li 
						.collapsible-header
							=i.descripcion
							%span.badge
								-if i.numero != 0
									faltan: #{i.numero} de #{i.numero_original}
								-else
									completado
						.collapsible-body
							%p
								-if i.assignments.size !=0
									-if i.completado
										Listo quedó asi:
									-else
										Hasta ahora:
									%br/
									-i.assignments.each do |as| 
										%b #{as.usuario}:
										#{as.cantidad}
										%br/
								-else
									Aún nadie se ha solidarizado 

app/views/incio/index.haml
.section.no-pad-bot#index-banner
	.container
		%br/
		%br/
		
		%h1.header.center.orange-text.show-on-small-only What 2 Bring
		.center.hide-on-small-only
			=image_tag("logo.jpeg",height: '300px',width:'auto')
		.row.center
			%ul
				%li 
					%h5 1) Crea un evento
				%li
					%h5 2) Agrega items
				%li
					%h5 3) Comparte el enlace
			%h4.header.col.s12.light Una forma diferente de organizar
		.row.center
			-#=link_to("Crear evento",new_event_path,:class=>"btn-large waves-effect waves-light orange")
			%a.btn-large.waves-effect.waves-light.orange.modal-trigger{:href => "#modal1"} Crear evento
		%br/
		%br/
.container
	.section
		.row
			.col.s12.m4
				.icon-block
					%h2.center.light-blue-text
						%i.material-icons event_note
					%h5.center Organización más efectiva
					%p.light La intención de w2b es ayudar como soporte para tener un mejor <b> control </b> sobre la organización de las lista de materiales en un evento.
			.col.s12.m4
				.icon-block
					%h2.center.light-blue-text
						%i.material-icons star_border
					%h5.center Fácil de usar
					%p.light Es muy intuitiva, basta con crear un evento y compartir en enlace con las personas que necesites.
			.col.s12.m4
				.icon-block
					%h2.center.light-blue-text
						%i.material-icons important_devices
					%h5.center Máxima compatibilidad
					%p.light El diseño fue una de nuestras prioridades al diseñar este sitio. Se adapta, <b>evoluciona</b>, para que accedas cómodamente desde el dispositivo que quieras.
	%br/
	%br/
.section#start
	.container
		.row.center
	%br/
	%br/
	%br/
%footer.page-footer.orange
	.container
		.row
			.col.l6.s12
				%h5 What 2 Bring
				%p.grey-text.text-lighten-4 Proyecto semestral  Agosto - Diciembre 2017
				%p.grey-text.text-lighten-4 ITESM CSF - Introducción a la ingeniería en tecnologías computacionales
	.footer-copyright
		.container
			%a.right.waves-effect.waves-light.btn.orange{:href => "https://github.com/robtry/w2b"} GITHUB

app/views/items/_form.html.haml
= form_for ([@event,@item]) do |f|
	.col.s12
		- if @item.errors.any?
			.red.lighten-2{style:"padding:10px"}
				%i.material-icons.left warning
				%h6= "#{pluralize(@item.errors.count, "problema(s)")} ocurrió al guardar el evento"
			-@item.errors.full_messages.each do |message|
				%script Materialize.toast("#{message}", 5000);
		.row
			.input-field.col.s12.l4
				%i.material-icons.prefix pie_chart_outlined
				= f.text_field :numero
				= f.label :numero, "Cantidad"
			.input-field.col.s12.l8
				%i.material-icons.prefix toc
				= f.text_field :descripcion
				= f.label :descripcion
			.input-field.col.s12
				%a.btn.waves-effect.waves-light.modal-trigger.red{:href => "#modal2"} Guardar item
				#modal2.modal
					.modal-content
						%h4.truncate ¿Esta seguro que desea agregar item?
						%ul
							%li *No va a poder editar este item posteriormente
							%li *No va a poder eliminar este item
					.modal-footer
						= f.submit 'Agregar', :class=>"btn"
						%a.modal-action.modal-close.waves-effect.waves-green.btn-flat REGRESAR

app/views/layouts/application.haml
!!!5
%html{lang: "es"}
	%head
		%meta{name:"viewport", content:"width=device-width, initial-scale=1"}
		%meta{charset:"UTF-8"}
		= favicon_link_tag 'favicon.ico'
		= csrf_meta_tags		
		= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
		%title What2Bring
%body
	.navbar-fixed
		%nav.light-blue.lighten-1{:role=>"navigation"}
			.nav-wrapper.container
				=link_to("W2B", root_path, :class=>"brand-logo")
				-#=image_tag("logo.png",height: '50px')
				%ul.right.hide-on-med-and-down
					%li
						-#=link_to("Nuevo evento <i class=\"material-icons right\"> add </i>".html_safe,new_event_path)
						%a.modal-trigger{:href => "#modal1"} Nuevo evento <i class="material-icons right"> add </i>
		-#=link_to("<i class=\"material-icons right\"> add </i>".html_safe,new_event_path, :class=>" btn-floating btn-large waves-effect waves-light red")
	#modal1.modal
		.modal-content
			%h4 Nuevo Evento
			-@event = Event.new
			= render 'events/form'
		.modal-footer
			%a.modal-action.modal-close.waves-effect.waves-green.btn-flat CERRAR
	=yield
	-flash.each do |_key, msg|
		%script	Materialize.toast("#{msg}", 5000);

app/views/layouts/application.html.haml
!!!5
%html{lang: "es"}
	%head
		%meta{name:"viewport", content:"width=device-width, initial-scale=1"}
		%meta{charset:"UTF-8"}
		-#= favicon_link_tag 'favicon.ico'
		= csrf_meta_tags		
		= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
		%title What2Bring
%body
	%nav.light-blue.lighten-1.navbar-fixed{:role=>"navigation"}
		%div.nav-wrapper.container
			%a.brand-logo#logo-container{:href => "#"} What2Bring
			%ul.right.hide-on-med-and-down
				%li
					%a{:href => "#"} Hola
			%ul#nav-mobile.side-nav
				%li
					%a{:href => "#"} navbar link
			%a.button-collapse{:href => "#",:data=>{:activates=>"nav-mobile"}}
				%i.material-icons menu
	=yield